version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:8080"
  postgres:
        image: postgres
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
        ports:
          - '5432:5432'
        volumes: 
          # copy the sql script to create tables
          - ./db/01-alunos.sql:/docker-entrypoint-initdb.d/create_tables.sql