version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"